name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      # Debuging secrets, remove later
      - name: Test printing your secret (Remove this step in production)
        run: |
          echo ${{ secrets.SONAR_TOKEN }} | sed 's/./& /g'
          echo ${{ secrets.SONAR_URL }} | sed 's/./& /g'
          echo ${{ secrets.SONAR_ORGANIZATION }} | sed 's/./& /g'
          echo ${{ secrets.SONAR_PROJECT_KEY }} | sed 's/./& /g'

      - name: Maven test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

    # Setup java 11 to be default (sonar-scanner requirement as 5.x)
      - name: Set Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
    # Setup sonar-scanner
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7  

    # Run sonar-scanner
      - name: SonarQube Scan
        run: sonar-scanner
          -Dsonar.host.url=https://sonarcloud.io/
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.sources=src/
          -Dsonar.junit.reportsPath=target/surefire-reports/
          -Dsonar.jacoco.reportsPath=target/jacoco.exec
          -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
          -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/

      

      